In [1]:
import pandas as pd
df = pd.read_csv("spam.csv")
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [3]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [5]:
df['spam'] = df['Category'].apply(lambda x :1 if x == 'spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [6]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(df.Message , df.spam , test_size = 0.25)

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [11]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count , y_train)

MultinomialNB()

In [12]:
emails = [
    'Hey Mohan , can we get together to watch football game tomorrow?',
    'Upto 20% discount on parking , exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [13]:
X_test_count = v.transform(X_test)
model.score(X_test_count , y_test)

0.9877961234745154

# Concept of pipe line

In [30]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer' , CountVectorizer()),
    ('nb' , MultinomialNB())
])

In [31]:
clf.fit(X_train , y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [32]:
clf.score(X_test , y_test)

0.9877961234745154

In [33]:
clf.predict(emails)

array([0, 1], dtype=int64)

In [26]:
>>> 

# Exercise

In [4]:
from sklearn.datasets import load_wine

In [7]:
wine = load_wine()

In [16]:
print(wine.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            10.6  30.0    19.5   3.3
    Ma

In [17]:
dir(wine)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [19]:
wine.data[:2]

array([[1.423e+01, 1.710e+00, 2.430e+00, 1.560e+01, 1.270e+02, 2.800e+00,
        3.060e+00, 2.800e-01, 2.290e+00, 5.640e+00, 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, 1.120e+01, 1.000e+02, 2.650e+00,
        2.760e+00, 2.600e-01, 1.280e+00, 4.380e+00, 1.050e+00, 3.400e+00,
        1.050e+03]])

In [20]:
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [23]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [26]:
wine.target[0:2]

array([0, 0])

In [27]:
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [38]:
import pandas as pd
df = pd.DataFrame(wine.data , columns = wine.feature_names)
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [40]:
df['target'] = wine.target
df[30:40]

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
30    13.73        1.50  2.70               22.5      101.0           3.00   
31    13.58        1.66  2.36               19.1      106.0           2.86   
32    13.68        1.83  2.36               17.2      104.0           2.42   
33    13.76        1.53  2.70               19.5      132.0           2.95   
34    13.51        1.80  2.65               19.0      110.0           2.35   
35    13.48        1.81  2.41               20.5      100.0           2.70   
36    13.28        1.64  2.84               15.5      110.0           2.60   
37    13.05        1.65  2.55               18.0       98.0           2.45   
38    13.07        1.50  2.10               15.5       98.0           2.40   
39    14.22        3.99  2.51               13.2      128.0           3.00   

    flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
30        3.25                  0.29             2.38             5.70  1.19   
31        3.19                  0.22             1.95             6.90  1.09   
32        2.69                  0.42             1.97             3.84  1.23   
33        2.74                  0.50             1.35             5.40  1.25   
34        2.53                  0.29             1.54             4.20  1.10   
35        2.98                  0.26             1.86             5.10  1.04   
36        2.68                  0.34             1.36             4.60  1.09   
37        2.43                  0.29             1.44             4.25  1.12   
38        2.64                  0.28             1.37             3.70  1.18   
39        3.04                  0.20             2.08             5.10  0.89   

    od280/od315_of_diluted_wines  proline  target  
30                          2.71   1285.0       0  
31                          2.88   1515.0       0  
32                          2.87    990.0       0  
33                          3.00   1235.0       0  
34                          2.87   1095.0       0  
35                          3.47    920.0       0  
36                          2.78    880.0       0  
37                          2.51   1105.0       0  
38                          2.69   1020.0       0  
39                          3.53    760.0       0

In [33]:
from sklearn.model_selection import train_test_split
X_train ,X_test , y_train , y_test = train_test_split(wine.data , wine.target , test_size = 0.3)

In [41]:
from sklearn.naive_bayes import GaussianNB , MultinomialNB
model = GaussianNB()

In [42]:
model.fit(X_train,y_train)

GaussianNB()

In [43]:
model.score(X_test , y_test)

1.0

In [44]:
mn = MultinomialNB()
mn.fit(X_train,y_train)
mn.score(X_test , y_test)

0.9629629629629629