In [3]:
import numpy as np

In [81]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a.ndim

2

In [7]:
a.shape

(2, 3)

In [8]:
a.reshape([3,2])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
#3-D array


a = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
a


array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [10]:
a.ndim

3

In [11]:
a.shape

(3, 1, 3)

In [12]:
### Dimension (3,2,3)

a = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
a

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [13]:
a.shape

(3, 2, 3)

In [14]:
a.itemsize  #return

4

In [15]:
a.dtype   #"dtypename bits"

dtype('int32')

In [16]:
a.size    #count of no. of elements

18

In [17]:
a = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]] , dtype = np.float16)
a

array([[[1., 2., 3.],
        [4., 5., 6.]],

       [[1., 2., 3.],
        [4., 5., 6.]],

       [[1., 2., 3.],
        [4., 5., 6.]]], dtype=float16)

In [18]:
a = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]] , dtype = complex)
a

array([[[1.+0.j, 2.+0.j, 3.+0.j],
        [4.+0.j, 5.+0.j, 6.+0.j]],

       [[1.+0.j, 2.+0.j, 3.+0.j],
        [4.+0.j, 5.+0.j, 6.+0.j]],

       [[1.+0.j, 2.+0.j, 3.+0.j],
        [4.+0.j, 5.+0.j, 6.+0.j]]])

In [19]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
l = range(5)
l

range(0, 5)

In [22]:
s = np.arange(1,5)
s

array([1, 2, 3, 4])

In [23]:
s = np.arange(1,5,2)
s

array([1, 3])

In [24]:
s = np.arange(3,9,5)
s

array([3, 8])

In [25]:
s = np.arange(9,1,-2)
s

array([9, 7, 5, 3])

In [26]:
x = np.linspace(1,5,10)            # ((5-1)/(10-1)= 0.444444444444)
x

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [27]:
y = np.linspace(1,5,5)
y

array([1., 2., 3., 4., 5.])

In [28]:
z = np.linspace(1,5,20)
z

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [31]:
k = np.linspace(2,10,12)
k

array([ 2.        ,  2.72727273,  3.45454545,  4.18181818,  4.90909091,
        5.63636364,  6.36363636,  7.09090909,  7.81818182,  8.54545455,
        9.27272727, 10.        ])

In [32]:

a = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
a

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [33]:
a.ndim

3

In [34]:
a.shape

(3, 2, 3)

In [35]:
a.reshape(3,3,2)

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]]])

In [36]:
a.reshape(3,1,6)

array([[[1, 2, 3, 4, 5, 6]],

       [[1, 2, 3, 4, 5, 6]],

       [[1, 2, 3, 4, 5, 6]]])

In [38]:
a.reshape(3,6,1)

array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6]],

       [[1],
        [2],
        [3],
        [4],
        [5],
        [6]],

       [[1],
        [2],
        [3],
        [4],
        [5],
        [6]]])

In [43]:
z = a.reshape(3,6,1)
z

array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6]],

       [[1],
        [2],
        [3],
        [4],
        [5],
        [6]],

       [[1],
        [2],
        [3],
        [4],
        [5],
        [6]]])

In [42]:
a


array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [44]:
z

array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6]],

       [[1],
        [2],
        [3],
        [4],
        [5],
        [6]],

       [[1],
        [2],
        [3],
        [4],
        [5],
        [6]]])

In [49]:
c = a.ravel()
c
c.ndim

1

In [47]:
a

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [50]:
a.min()

1

In [51]:
a.max()

6

In [52]:
a.sum()

63

In [57]:
a.sum(axis = 0)  # sum along the row

array([[ 3,  6,  9],
       [12, 15, 18]])

In [58]:
np.sqrt(a)

array([[[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]],

       [[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]],

       [[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]]])

In [59]:
np.std(a)

1.707825127659933

In [60]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
a+b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [74]:
a-b

array([[0, 0, 0],
       [0, 0, 0]])

In [75]:
a*b

array([[ 1,  4,  9],
       [16, 25, 36]])

In [76]:
a/b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [80]:
a = np.array([[1,2,3],[4,5,6]])
a
b = np.array([[1,2,3],[4,5,6]])
b


r = np.dot(a.T,b)
r

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])