## Linear_Regression_Multiple_Variables

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model as lm

In [2]:
df = pd.read_csv('homeprices1.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [3]:
df['bedrooms']

0    3.0
1    4.0
2    NaN
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [4]:
import math
median_bedroom = math.floor(df['bedrooms'].median()) 
median_bedroom

4

In [5]:
df['bedrooms'] = df['bedrooms'].fillna(median_bedroom)
df['bedrooms']

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [6]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
reg = lm.LinearRegression()
reg.fit(df[['area' , 'bedrooms' , 'age']].values , df.price)

LinearRegression()

In [8]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [9]:
reg.intercept_

221323.00186540384

In [10]:
# y = m1x1 + m2x2 + m3x3 +  b
3000 * 112.06244194 +  4.0 * 23388.88007794 + 15 *  -3231.71790863   +  221323.00186540384 

602590.0793677138

In [11]:
reg.predict([[3000 , 4.0 , 15]])

array([602590.07937407])

In [12]:
reg.predict([[6000 , 8.0 , 7.5]])

array([1056570.80982698])

## Exercise


In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model as lm

In [14]:
df = pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [15]:
import math
test_median = df['test_score(out of 10)'].median()
test_median

8.0

In [16]:
df.fillna({
    'experience': 'zero',
    'test_score(out of 10)' : test_median, 
} ,inplace = True)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [17]:
pip install word2number

Note: you may need to restart the kernel to use updated packages.


In [18]:
from word2number import w2n

In [19]:
df['experience'] = df['experience'].astype(str) 
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [20]:
df["experience"] = df.experience.astype(str)
df.experience = df.experience.apply(w2n.word_to_num)
df['experience']


0     0
1     0
2     5
3     2
4     7
5     3
6    10
7    11
Name: experience, dtype: int64

In [21]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [22]:
reg  = lm.LinearRegression()
reg.fit(df[['experience' ,'test_score(out of 10)' , 'interview_score(out of 10)']].values , df['salary($)'])

LinearRegression()

In [23]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [24]:
reg.intercept_

17737.263464337688

In [25]:
reg.predict([[2,9,6]])

array([53205.96797671])

In [26]:
reg.predict([[12,10,10]])

array([92002.18340611])



## Saving model to a file

In [38]:
# 1st way

import pickle

In [39]:
with open('model_pickle' , 'wb') as f:
    pickle.dump(reg,f)

In [40]:
with open('model_pickle' , 'rb') as f :
    mp = pickle.load(f)

In [41]:
mp.predict([[2,9,6]])

array([53205.96797671])

In [55]:
!pip install joblib

In [59]:
# 2nd way

import joblib

In [60]:
joblib.dump(reg , 'model_joblib')

['model_joblib']

In [63]:
mj = joblib.load('model_joblib')

In [64]:
mj.predict([[2,9,6]])

array([53205.96797671])